name: pydata2021-eda
channels:
  - conda-forge
  - defaults
dependencies:
  - autoviz
  - dtale
  - ipywidgets
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pandas_profiling
  - pip
  - plotly
  - python=3.8.*
  - seaborn
  - sweetviz
