name: pydata2021-eda
channels:
  - conda-forge
  - defaults
dependencies:
  - autoviz
  - dtale
  - ipywidgets
  - jupyter
  - matplotlib
  - missingno
  - numpy
  - pandas
  - pandas-profiling
  - pip
  - plotly
  - pyarrow
  - python=3.8.*
  - seaborn
  - sidetable
  - sweetviz
  - wordcloud
